[project]
name = "lpdm"
description = "Latent Physics Diffusion Model"
version = "0.0.0"
dependencies = [
  "einops==0.8.0",
  "numpy==1.26.4",
  "torch==2.3.1",
  "torchvision==0.18.1",
]

[project.optional-dependencies]
all = [
  "neptune==1.11.1",
  "pre-commit==3.8.0",
  "pytest==8.3.2",
  "ruff==0.6.4",
]

[tool.ruff]
extend-include = ["*.ipynb"]
line-length = 99

[tool.ruff.lint]
extend-select = ["B", "I", "W"]
ignore = ["E731", "E741"]

[tool.ruff.lint.isort]
lines-between-types = 1
no-sections = true
relative-imports-order = "closest-to-furthest"

[tool.ruff.format]
preview = true

[tool.setuptools.packages.find]
include = ["lpdm*"]
